// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAvitoAccount = `-- name: DeleteAvitoAccount :one
DELETE FROM avito_accounts
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteAvitoAccount(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAvitoAccount, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteProxy = `-- name: DeleteProxy :one
DELETE FROM proxies
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteProxy(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProxy, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getActiveSessionByHash = `-- name: GetActiveSessionByHash :one
SELECT
    s.id,
    s.user_id,
    s.token_hash,
    s.expires_at,
    s.revoked_at,
    s.created_at,
    u.email,
    u.role
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
`

type GetActiveSessionByHashRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Email     string             `json:"email"`
	Role      UserRole           `json:"role"`
}

func (q *Queries) GetActiveSessionByHash(ctx context.Context, tokenHash string) (GetActiveSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByHash, tokenHash)
	var i GetActiveSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, role
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const listAllProxies = `-- name: ListAllProxies :many
SELECT id, endpoint, status, created_at, label, last_ok_at, last_err, fail_streak, health
FROM proxies
ORDER BY created_at ASC
`

func (q *Queries) ListAllProxies(ctx context.Context) ([]Proxy, error) {
	rows, err := q.db.Query(ctx, listAllProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.Status,
			&i.CreatedAt,
			&i.Label,
			&i.LastOkAt,
			&i.LastErr,
			&i.FailStreak,
			&i.Health,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvitoAccounts = `-- name: ListAvitoAccounts :many
SELECT id, label, status, external_ref, created_at, updated_at
FROM avito_accounts
ORDER BY created_at ASC
`

func (q *Queries) ListAvitoAccounts(ctx context.Context) ([]AvitoAccount, error) {
	rows, err := q.db.Query(ctx, listAvitoAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvitoAccount{}
	for rows.Next() {
		var i AvitoAccount
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.ExternalRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickActiveAvitoAccount = `-- name: PickActiveAvitoAccount :one
SELECT a.id, a.label, a.external_ref, s.password
FROM avito_accounts a
JOIN avito_account_secrets s ON s.account_id = a.id
WHERE a.status = 'ACTIVE'
ORDER BY a.created_at ASC
LIMIT 1
`

type PickActiveAvitoAccountRow struct {
	ID          pgtype.UUID `json:"id"`
	Label       string      `json:"label"`
	ExternalRef string      `json:"external_ref"`
	Password    string      `json:"password"`
}

func (q *Queries) PickActiveAvitoAccount(ctx context.Context) (PickActiveAvitoAccountRow, error) {
	row := q.db.QueryRow(ctx, pickActiveAvitoAccount)
	var i PickActiveAvitoAccountRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.ExternalRef,
		&i.Password,
	)
	return i, err
}

const revokeSessionByHash = `-- name: RevokeSessionByHash :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByHash, tokenHash)
	return err
}

const updateAvitoAccount = `-- name: UpdateAvitoAccount :one
UPDATE avito_accounts
SET label = $2,
    status = $3,
    external_ref = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, label, status, external_ref, created_at, updated_at
`

type UpdateAvitoAccountParams struct {
	ID          pgtype.UUID        `json:"id"`
	Label       string             `json:"label"`
	Status      AvitoAccountStatus `json:"status"`
	ExternalRef string             `json:"external_ref"`
}

func (q *Queries) UpdateAvitoAccount(ctx context.Context, arg UpdateAvitoAccountParams) (AvitoAccount, error) {
	row := q.db.QueryRow(ctx, updateAvitoAccount,
		arg.ID,
		arg.Label,
		arg.Status,
		arg.ExternalRef,
	)
	var i AvitoAccount
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProxy = `-- name: UpdateProxy :one
UPDATE proxies
SET endpoint = $2,
    status = $3,
    label = $4
WHERE id = $1
RETURNING id, endpoint, status, created_at, label, last_ok_at, last_err, fail_streak, health
`

type UpdateProxyParams struct {
	ID       pgtype.UUID `json:"id"`
	Endpoint string      `json:"endpoint"`
	Status   ProxyStatus `json:"status"`
	Label    string      `json:"label"`
}

func (q *Queries) UpdateProxy(ctx context.Context, arg UpdateProxyParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, updateProxy,
		arg.ID,
		arg.Endpoint,
		arg.Status,
		arg.Label,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.Status,
		&i.CreatedAt,
		&i.Label,
		&i.LastOkAt,
		&i.LastErr,
		&i.FailStreak,
		&i.Health,
	)
	return i, err
}

const upsertAvitoAccountSecret = `-- name: UpsertAvitoAccountSecret :exec
INSERT INTO avito_account_secrets (account_id, password)
VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE
SET password = EXCLUDED.password,
    updated_at = now()
`

type UpsertAvitoAccountSecretParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Password  string      `json:"password"`
}

func (q *Queries) UpsertAvitoAccountSecret(ctx context.Context, arg UpsertAvitoAccountSecretParams) error {
	_, err := q.db.Exec(ctx, upsertAvitoAccountSecret, arg.AccountID, arg.Password)
	return err
}
