// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bindings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBinding = `-- name: CreateBinding :one
INSERT INTO listing_fetch_bindings (avito_account_id, proxy_id, user_data_dir, status, session_status)
VALUES ($1, $2, $3, 'ACTIVE', 'LOGGED_OUT')
RETURNING id, avito_account_id, proxy_id, user_data_dir, status, session_status, session_err, last_session_at, created_at
`

type CreateBindingParams struct {
	AvitoAccountID pgtype.UUID `json:"avito_account_id"`
	ProxyID        pgtype.UUID `json:"proxy_id"`
	UserDataDir    string      `json:"user_data_dir"`
}

func (q *Queries) CreateBinding(ctx context.Context, arg CreateBindingParams) (ListingFetchBinding, error) {
	row := q.db.QueryRow(ctx, createBinding, arg.AvitoAccountID, arg.ProxyID, arg.UserDataDir)
	var i ListingFetchBinding
	err := row.Scan(
		&i.ID,
		&i.AvitoAccountID,
		&i.ProxyID,
		&i.UserDataDir,
		&i.Status,
		&i.SessionStatus,
		&i.SessionErr,
		&i.LastSessionAt,
		&i.CreatedAt,
	)
	return i, err
}

const forceProxyDegraded = `-- name: ForceProxyDegraded :exec
UPDATE proxies
SET health = 'DEGRADED'
WHERE id = $1
`

func (q *Queries) ForceProxyDegraded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, forceProxyDegraded, id)
	return err
}

const getBinding = `-- name: GetBinding :one
SELECT id, avito_account_id, proxy_id, user_data_dir, status, session_status, session_err, last_session_at, created_at
FROM listing_fetch_bindings
WHERE id = $1
`

func (q *Queries) GetBinding(ctx context.Context, id pgtype.UUID) (ListingFetchBinding, error) {
	row := q.db.QueryRow(ctx, getBinding, id)
	var i ListingFetchBinding
	err := row.Scan(
		&i.ID,
		&i.AvitoAccountID,
		&i.ProxyID,
		&i.UserDataDir,
		&i.Status,
		&i.SessionStatus,
		&i.SessionErr,
		&i.LastSessionAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProxy = `-- name: GetProxy :one
SELECT id, endpoint, status, created_at, label, last_ok_at, last_err, fail_streak, health
FROM proxies
WHERE id = $1
`

func (q *Queries) GetProxy(ctx context.Context, id pgtype.UUID) (Proxy, error) {
	row := q.db.QueryRow(ctx, getProxy, id)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.Status,
		&i.CreatedAt,
		&i.Label,
		&i.LastOkAt,
		&i.LastErr,
		&i.FailStreak,
		&i.Health,
	)
	return i, err
}

const listBindings = `-- name: ListBindings :many
SELECT id, avito_account_id, proxy_id, user_data_dir, status, session_status, session_err, last_session_at, created_at
FROM listing_fetch_bindings
ORDER BY created_at ASC
`

func (q *Queries) ListBindings(ctx context.Context) ([]ListingFetchBinding, error) {
	rows, err := q.db.Query(ctx, listBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingFetchBinding{}
	for rows.Next() {
		var i ListingFetchBinding
		if err := rows.Scan(
			&i.ID,
			&i.AvitoAccountID,
			&i.ProxyID,
			&i.UserDataDir,
			&i.Status,
			&i.SessionStatus,
			&i.SessionErr,
			&i.LastSessionAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseBindingsForProxy = `-- name: PauseBindingsForProxy :exec
UPDATE listing_fetch_bindings
SET status = 'PAUSED'
WHERE proxy_id = $1
  AND status = 'ACTIVE'
`

func (q *Queries) PauseBindingsForProxy(ctx context.Context, proxyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pauseBindingsForProxy, proxyID)
	return err
}

const pickReadyBinding = `-- name: PickReadyBinding :one
SELECT
    b.id,
    b.avito_account_id,
    b.proxy_id,
    b.user_data_dir,
    b.status,
    b.session_status,
    b.session_err,
    b.last_session_at,
    b.created_at,
    p.endpoint AS proxy_endpoint
FROM listing_fetch_bindings b
JOIN proxies p ON p.id = b.proxy_id
WHERE b.status = 'ACTIVE'
  AND b.session_status = 'READY'
  AND p.status = 'ACTIVE'
  AND p.health <> 'DEAD'
ORDER BY b.created_at ASC
LIMIT 1
`

type PickReadyBindingRow struct {
	ID             pgtype.UUID          `json:"id"`
	AvitoAccountID pgtype.UUID          `json:"avito_account_id"`
	ProxyID        pgtype.UUID          `json:"proxy_id"`
	UserDataDir    string               `json:"user_data_dir"`
	Status         ListingBindingStatus `json:"status"`
	SessionStatus  ListingSessionStatus `json:"session_status"`
	SessionErr     *string              `json:"session_err"`
	LastSessionAt  pgtype.Timestamptz   `json:"last_session_at"`
	CreatedAt      pgtype.Timestamptz   `json:"created_at"`
	ProxyEndpoint  string               `json:"proxy_endpoint"`
}

func (q *Queries) PickReadyBinding(ctx context.Context) (PickReadyBindingRow, error) {
	row := q.db.QueryRow(ctx, pickReadyBinding)
	var i PickReadyBindingRow
	err := row.Scan(
		&i.ID,
		&i.AvitoAccountID,
		&i.ProxyID,
		&i.UserDataDir,
		&i.Status,
		&i.SessionStatus,
		&i.SessionErr,
		&i.LastSessionAt,
		&i.CreatedAt,
		&i.ProxyEndpoint,
	)
	return i, err
}

const recordProxyHealthFail = `-- name: RecordProxyHealthFail :one
UPDATE proxies
SET last_err = $1,
    fail_streak = fail_streak + 1,
    health = CASE
        WHEN fail_streak + 1 >= $2::int THEN 'DEAD'::proxy_health_status
        ELSE 'DEGRADED'::proxy_health_status
    END
WHERE id = $3
RETURNING id, endpoint, status, created_at, label, last_ok_at, last_err, fail_streak, health
`

type RecordProxyHealthFailParams struct {
	LastErr   *string     `json:"last_err"`
	DeadAfter int32       `json:"dead_after"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) RecordProxyHealthFail(ctx context.Context, arg RecordProxyHealthFailParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, recordProxyHealthFail, arg.LastErr, arg.DeadAfter, arg.ID)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.Status,
		&i.CreatedAt,
		&i.Label,
		&i.LastOkAt,
		&i.LastErr,
		&i.FailStreak,
		&i.Health,
	)
	return i, err
}

const recordProxyHealthOK = `-- name: RecordProxyHealthOK :exec
UPDATE proxies
SET health = 'OK',
    last_ok_at = now(),
    last_err = NULL,
    fail_streak = 0
WHERE id = $1
`

func (q *Queries) RecordProxyHealthOK(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordProxyHealthOK, id)
	return err
}

const updateBindingSession = `-- name: UpdateBindingSession :one
UPDATE listing_fetch_bindings
SET session_status = $2,
    session_err = $3,
    last_session_at = now()
WHERE id = $1
RETURNING id, avito_account_id, proxy_id, user_data_dir, status, session_status, session_err, last_session_at, created_at
`

type UpdateBindingSessionParams struct {
	ID            pgtype.UUID          `json:"id"`
	SessionStatus ListingSessionStatus `json:"session_status"`
	SessionErr    *string              `json:"session_err"`
}

func (q *Queries) UpdateBindingSession(ctx context.Context, arg UpdateBindingSessionParams) (ListingFetchBinding, error) {
	row := q.db.QueryRow(ctx, updateBindingSession, arg.ID, arg.SessionStatus, arg.SessionErr)
	var i ListingFetchBinding
	err := row.Scan(
		&i.ID,
		&i.AvitoAccountID,
		&i.ProxyID,
		&i.UserDataDir,
		&i.Status,
		&i.SessionStatus,
		&i.SessionErr,
		&i.LastSessionAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateBindingStatus = `-- name: UpdateBindingStatus :one
UPDATE listing_fetch_bindings
SET status = $2
WHERE id = $1
RETURNING id, avito_account_id, proxy_id, user_data_dir, status, session_status, session_err, last_session_at, created_at
`

type UpdateBindingStatusParams struct {
	ID     pgtype.UUID          `json:"id"`
	Status ListingBindingStatus `json:"status"`
}

func (q *Queries) UpdateBindingStatus(ctx context.Context, arg UpdateBindingStatusParams) (ListingFetchBinding, error) {
	row := q.db.QueryRow(ctx, updateBindingStatus, arg.ID, arg.Status)
	var i ListingFetchBinding
	err := row.Scan(
		&i.ID,
		&i.AvitoAccountID,
		&i.ProxyID,
		&i.UserDataDir,
		&i.Status,
		&i.SessionStatus,
		&i.SessionErr,
		&i.LastSessionAt,
		&i.CreatedAt,
	)
	return i, err
}
