// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserTasks = `-- name: CountUserTasks :one
SELECT count(*)::bigint AS count
FROM tasks
WHERE user_id = $1
  AND status IN ('PENDING', 'RUNNING', 'PAUSED')
`

func (q *Queries) CountUserTasks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProxy = `-- name: CreateProxy :one
INSERT INTO proxies (endpoint, status, label)
VALUES ($1, $2, $3)
RETURNING id, endpoint, status, created_at, label
`

type CreateProxyParams struct {
	Endpoint string      `json:"endpoint"`
	Status   ProxyStatus `json:"status"`
	Label    string      `json:"label"`
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, createProxy, arg.Endpoint, arg.Status, arg.Label)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.Status,
		&i.CreatedAt,
		&i.Label,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, plan_type, active)
VALUES ($1, $2, true)
RETURNING id, user_id, plan_type, active, created_at
`

type CreateSubscriptionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PlanType PlanType    `json:"plan_type"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.PlanType)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanType,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, query, status)
VALUES ($1, $2, 'PENDING')
RETURNING id, user_id, query, status, created_at
`

type CreateTaskParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Query  string      `json:"query"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.UserID, arg.Query)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email)
VALUES ($1)
RETURNING id, email, created_at, role
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, user_id, plan_type, active, created_at
FROM subscriptions
WHERE user_id = $1 AND active = true
`

func (q *Queries) GetActiveSubscription(ctx context.Context, userID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanType,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSubscriptionForUpdate = `-- name: GetActiveSubscriptionForUpdate :one
SELECT
    s.id,
    s.user_id,
    s.plan_type,
    s.active,
    s.created_at,
    pl.max_tasks
FROM subscriptions s
JOIN plan_limits pl ON s.plan_type = pl.plan_type
WHERE s.user_id = $1 AND s.active = true
FOR UPDATE OF s
`

type GetActiveSubscriptionForUpdateRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	PlanType  PlanType           `json:"plan_type"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MaxTasks  int32              `json:"max_tasks"`
}

func (q *Queries) GetActiveSubscriptionForUpdate(ctx context.Context, userID pgtype.UUID) (GetActiveSubscriptionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionForUpdate, userID)
	var i GetActiveSubscriptionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanType,
		&i.Active,
		&i.CreatedAt,
		&i.MaxTasks,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO items (avito_id, title)
VALUES ($1, $2)
RETURNING id, avito_id, title, created_at
`

type InsertItemParams struct {
	AvitoID string `json:"avito_id"`
	Title   string `json:"title"`
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem, arg.AvitoID, arg.Title)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.AvitoID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveProxies = `-- name: ListActiveProxies :many
SELECT id, endpoint, status, created_at, label
FROM proxies
WHERE status = 'ACTIVE'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveProxies(ctx context.Context) ([]Proxy, error) {
	rows, err := q.db.Query(ctx, listActiveProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.Status,
			&i.CreatedAt,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
