// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing_search.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingTask = `-- name: ClaimNextPendingTask :one
WITH picked AS (
    SELECT id
    FROM tasks
    WHERE status = 'PENDING'
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE tasks t
SET status = 'RUNNING'
FROM picked
WHERE t.id = picked.id
RETURNING t.id, t.user_id, t.query, t.status, t.created_at
`

func (q *Queries) ClaimNextPendingTask(ctx context.Context) (Task, error) {
	row := q.db.QueryRow(ctx, claimNextPendingTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const countTaskItems = `-- name: CountTaskItems :one
SELECT count(*)::bigint AS count
FROM task_items
WHERE task_id = $1
`

func (q *Queries) CountTaskItems(ctx context.Context, taskID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTaskItems, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, query, status, created_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertFilterSeen = `-- name: InsertFilterSeen :exec
INSERT INTO listing_filter_seen (user_id, filter_key, avito_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertFilterSeenParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	FilterKey string      `json:"filter_key"`
	AvitoID   string      `json:"avito_id"`
}

func (q *Queries) InsertFilterSeen(ctx context.Context, arg InsertFilterSeenParams) error {
	_, err := q.db.Exec(ctx, insertFilterSeen, arg.UserID, arg.FilterKey, arg.AvitoID)
	return err
}

const insertTaskItem = `-- name: InsertTaskItem :exec
INSERT INTO task_items (task_id, item_id, rank)
VALUES ($1, $2, $3)
`

type InsertTaskItemParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	ItemID pgtype.UUID `json:"item_id"`
	Rank   int32       `json:"rank"`
}

func (q *Queries) InsertTaskItem(ctx context.Context, arg InsertTaskItemParams) error {
	_, err := q.db.Exec(ctx, insertTaskItem, arg.TaskID, arg.ItemID, arg.Rank)
	return err
}

const listFilterSeenAvitoIDs = `-- name: ListFilterSeenAvitoIDs :many
SELECT avito_id
FROM listing_filter_seen
WHERE user_id = $1
  AND filter_key = $2
`

type ListFilterSeenAvitoIDsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	FilterKey string      `json:"filter_key"`
}

func (q *Queries) ListFilterSeenAvitoIDs(ctx context.Context, arg ListFilterSeenAvitoIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listFilterSeenAvitoIDs, arg.UserID, arg.FilterKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var avito_id string
		if err := rows.Scan(&avito_id); err != nil {
			return nil, err
		}
		items = append(items, avito_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriorAvitoIDsForUserCompletedTasks = `-- name: ListPriorAvitoIDsForUserCompletedTasks :many
SELECT t.query, i.avito_id
FROM tasks t
JOIN task_items ti ON ti.task_id = t.id
JOIN items i ON i.id = ti.item_id
WHERE t.user_id = $1
  AND t.status = 'COMPLETED'
  AND t.id != $2
`

type ListPriorAvitoIDsForUserCompletedTasksParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type ListPriorAvitoIDsForUserCompletedTasksRow struct {
	Query   string `json:"query"`
	AvitoID string `json:"avito_id"`
}

func (q *Queries) ListPriorAvitoIDsForUserCompletedTasks(ctx context.Context, arg ListPriorAvitoIDsForUserCompletedTasksParams) ([]ListPriorAvitoIDsForUserCompletedTasksRow, error) {
	rows, err := q.db.Query(ctx, listPriorAvitoIDsForUserCompletedTasks, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriorAvitoIDsForUserCompletedTasksRow{}
	for rows.Next() {
		var i ListPriorAvitoIDsForUserCompletedTasksRow
		if err := rows.Scan(&i.Query, &i.AvitoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriorAvitoIDsForUserQuery = `-- name: ListPriorAvitoIDsForUserQuery :many
SELECT DISTINCT i.avito_id
FROM tasks t
JOIN task_items ti ON ti.task_id = t.id
JOIN items i ON i.id = ti.item_id
WHERE t.user_id = $1
  AND t.query = $2
  AND t.status = 'COMPLETED'
  AND t.id != $3
`

type ListPriorAvitoIDsForUserQueryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Query  string      `json:"query"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) ListPriorAvitoIDsForUserQuery(ctx context.Context, arg ListPriorAvitoIDsForUserQueryParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPriorAvitoIDsForUserQuery, arg.UserID, arg.Query, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var avito_id string
		if err := rows.Scan(&avito_id); err != nil {
			return nil, err
		}
		items = append(items, avito_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskItems = `-- name: ListTaskItems :many
SELECT
    i.id,
    i.avito_id,
    i.title,
    i.created_at,
    ti.rank
FROM task_items ti
JOIN items i ON i.id = ti.item_id
WHERE ti.task_id = $1
ORDER BY ti.rank ASC
`

type ListTaskItemsRow struct {
	ID        pgtype.UUID        `json:"id"`
	AvitoID   string             `json:"avito_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Rank      int32              `json:"rank"`
}

func (q *Queries) ListTaskItems(ctx context.Context, taskID pgtype.UUID) ([]ListTaskItemsRow, error) {
	rows, err := q.db.Query(ctx, listTaskItems, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskItemsRow{}
	for rows.Next() {
		var i ListTaskItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AvitoID,
			&i.Title,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, user_id, query, status, created_at
FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTasksByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Query,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2
WHERE id = $1
RETURNING id, user_id, query, status, created_at
`

type UpdateTaskStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status TaskStatus  `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
