// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing_watches.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFilterWatch = `-- name: GetFilterWatch :one
SELECT id, user_id, filter_key, query, status, last_polled_at, created_at
FROM listing_filter_watches
WHERE id = $1
`

func (q *Queries) GetFilterWatch(ctx context.Context, id pgtype.UUID) (ListingFilterWatch, error) {
	row := q.db.QueryRow(ctx, getFilterWatch, id)
	var i ListingFilterWatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FilterKey,
		&i.Query,
		&i.Status,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFilterWatchForUser = `-- name: GetFilterWatchForUser :one
SELECT id, user_id, filter_key, query, status, last_polled_at, created_at
FROM listing_filter_watches
WHERE id = $1
  AND user_id = $2
`

type GetFilterWatchForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetFilterWatchForUser(ctx context.Context, arg GetFilterWatchForUserParams) (ListingFilterWatch, error) {
	row := q.db.QueryRow(ctx, getFilterWatchForUser, arg.ID, arg.UserID)
	var i ListingFilterWatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FilterKey,
		&i.Query,
		&i.Status,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWatchHit = `-- name: InsertWatchHit :exec
INSERT INTO listing_watch_hits (watch_id, item_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertWatchHitParams struct {
	WatchID pgtype.UUID `json:"watch_id"`
	ItemID  pgtype.UUID `json:"item_id"`
}

func (q *Queries) InsertWatchHit(ctx context.Context, arg InsertWatchHitParams) error {
	_, err := q.db.Exec(ctx, insertWatchHit, arg.WatchID, arg.ItemID)
	return err
}

const listDueFilterWatches = `-- name: ListDueFilterWatches :many
SELECT id, user_id, filter_key, query, status, last_polled_at, created_at
FROM listing_filter_watches
WHERE status = 'ACTIVE'
  AND (
    last_polled_at IS NULL
    OR last_polled_at <= now() - interval '1 minute'
  )
ORDER BY last_polled_at NULLS FIRST, created_at ASC
LIMIT 20
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListDueFilterWatches(ctx context.Context) ([]ListingFilterWatch, error) {
	rows, err := q.db.Query(ctx, listDueFilterWatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingFilterWatch{}
	for rows.Next() {
		var i ListingFilterWatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FilterKey,
			&i.Query,
			&i.Status,
			&i.LastPolledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchHits = `-- name: ListWatchHits :many
SELECT
    i.id,
    i.avito_id,
    i.title,
    i.created_at,
    wh.found_at
FROM listing_watch_hits wh
JOIN items i ON i.id = wh.item_id
WHERE wh.watch_id = $1
ORDER BY wh.found_at DESC
`

type ListWatchHitsRow struct {
	ID        pgtype.UUID        `json:"id"`
	AvitoID   string             `json:"avito_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	FoundAt   pgtype.Timestamptz `json:"found_at"`
}

func (q *Queries) ListWatchHits(ctx context.Context, watchID pgtype.UUID) ([]ListWatchHitsRow, error) {
	rows, err := q.db.Query(ctx, listWatchHits, watchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWatchHitsRow{}
	for rows.Next() {
		var i ListWatchHitsRow
		if err := rows.Scan(
			&i.ID,
			&i.AvitoID,
			&i.Title,
			&i.CreatedAt,
			&i.FoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchFilterWatchPolled = `-- name: TouchFilterWatchPolled :exec
UPDATE listing_filter_watches
SET last_polled_at = now()
WHERE id = $1
`

func (q *Queries) TouchFilterWatchPolled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchFilterWatchPolled, id)
	return err
}

const upsertFilterWatch = `-- name: UpsertFilterWatch :one
INSERT INTO listing_filter_watches (user_id, filter_key, query, status)
VALUES ($1, $2, $3, 'ACTIVE')
ON CONFLICT (user_id, filter_key) DO UPDATE
SET query = EXCLUDED.query,
    status = 'ACTIVE',
    last_polled_at = NULL
RETURNING id, user_id, filter_key, query, status, last_polled_at, created_at
`

type UpsertFilterWatchParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	FilterKey string      `json:"filter_key"`
	Query     string      `json:"query"`
}

func (q *Queries) UpsertFilterWatch(ctx context.Context, arg UpsertFilterWatchParams) (ListingFilterWatch, error) {
	row := q.db.QueryRow(ctx, upsertFilterWatch, arg.UserID, arg.FilterKey, arg.Query)
	var i ListingFilterWatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FilterKey,
		&i.Query,
		&i.Status,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}
