// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing_search.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingTask = `-- name: ClaimNextPendingTask :one
WITH picked AS (
    SELECT id
    FROM tasks
    WHERE status = 'PENDING'
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE tasks t
SET status = 'RUNNING'
FROM picked
WHERE t.id = picked.id
RETURNING t.id, t.user_id, t.query, t.status, t.created_at
`

func (q *Queries) ClaimNextPendingTask(ctx context.Context) (Task, error) {
	row := q.db.QueryRow(ctx, claimNextPendingTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const countTaskItems = `-- name: CountTaskItems :one
SELECT count(*)::bigint AS count
FROM task_items
WHERE task_id = $1
`

func (q *Queries) CountTaskItems(ctx context.Context, taskID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTaskItems, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, query, status, created_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertTaskItem = `-- name: InsertTaskItem :exec
INSERT INTO task_items (task_id, item_id, rank)
VALUES ($1, $2, $3)
`

type InsertTaskItemParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	ItemID pgtype.UUID `json:"item_id"`
	Rank   int32       `json:"rank"`
}

func (q *Queries) InsertTaskItem(ctx context.Context, arg InsertTaskItemParams) error {
	_, err := q.db.Exec(ctx, insertTaskItem, arg.TaskID, arg.ItemID, arg.Rank)
	return err
}

const listTaskItems = `-- name: ListTaskItems :many
SELECT
    i.id,
    i.avito_id,
    i.title,
    i.created_at,
    ti.rank
FROM task_items ti
JOIN items i ON i.id = ti.item_id
WHERE ti.task_id = $1
ORDER BY ti.rank ASC
`

type ListTaskItemsRow struct {
	ID        pgtype.UUID        `json:"id"`
	AvitoID   string             `json:"avito_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Rank      int32              `json:"rank"`
}

func (q *Queries) ListTaskItems(ctx context.Context, taskID pgtype.UUID) ([]ListTaskItemsRow, error) {
	rows, err := q.db.Query(ctx, listTaskItems, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskItemsRow{}
	for rows.Next() {
		var i ListTaskItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AvitoID,
			&i.Title,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2
WHERE id = $1
RETURNING id, user_id, query, status, created_at
`

type UpdateTaskStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status TaskStatus  `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
