// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingNotifications = `-- name: ClaimPendingNotifications :many
SELECT
    o.id,
    o.user_id,
    o.watch_id,
    o.item_id,
    o.channel,
    o.status,
    o.attempts,
    o.last_error,
    o.created_at,
    i.title AS item_title,
    i.avito_id AS item_avito_id,
    s.telegram_chat_id,
    COALESCE(s.enabled, false) AS notify_enabled
FROM notification_outbox o
JOIN items i ON i.id = o.item_id
LEFT JOIN user_notification_settings s ON s.user_id = o.user_id
WHERE o.status IN ('PENDING', 'FAILED')
ORDER BY o.created_at ASC
LIMIT $1
FOR UPDATE OF o SKIP LOCKED
`

type ClaimPendingNotificationsRow struct {
	ID             pgtype.UUID              `json:"id"`
	UserID         pgtype.UUID              `json:"user_id"`
	WatchID        pgtype.UUID              `json:"watch_id"`
	ItemID         pgtype.UUID              `json:"item_id"`
	Channel        NotificationChannel      `json:"channel"`
	Status         NotificationOutboxStatus `json:"status"`
	Attempts       int32                    `json:"attempts"`
	LastError      *string                  `json:"last_error"`
	CreatedAt      pgtype.Timestamptz       `json:"created_at"`
	ItemTitle      string                   `json:"item_title"`
	ItemAvitoID    string                   `json:"item_avito_id"`
	TelegramChatID *string                  `json:"telegram_chat_id"`
	NotifyEnabled  bool                     `json:"notify_enabled"`
}

func (q *Queries) ClaimPendingNotifications(ctx context.Context, limit int32) ([]ClaimPendingNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingNotificationsRow{}
	for rows.Next() {
		var i ClaimPendingNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WatchID,
			&i.ItemID,
			&i.Channel,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.ItemTitle,
			&i.ItemAvitoID,
			&i.TelegramChatID,
			&i.NotifyEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO notification_outbox (user_id, watch_id, item_id, channel, status)
VALUES ($1, $2, $3, 'TELEGRAM', 'PENDING')
ON CONFLICT (watch_id, item_id, channel) DO NOTHING
`

type EnqueueNotificationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	WatchID pgtype.UUID `json:"watch_id"`
	ItemID  pgtype.UUID `json:"item_id"`
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification, arg.UserID, arg.WatchID, arg.ItemID)
	return err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT user_id, telegram_chat_id, enabled, updated_at
FROM user_notification_settings
WHERE user_id = $1
`

func (q *Queries) GetNotificationSettings(ctx context.Context, userID pgtype.UUID) (UserNotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettings, userID)
	var i UserNotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.TelegramChatID,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationDone = `-- name: MarkNotificationDone :exec
UPDATE notification_outbox
SET status = 'DONE',
    last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkNotificationDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationDone, id)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notification_outbox
SET status = 'FAILED',
    last_error = $2,
    attempts = attempts + 1
WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError *string     `json:"last_error"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.LastError)
	return err
}

const markNotificationSubmitted = `-- name: MarkNotificationSubmitted :exec
UPDATE notification_outbox
SET status = 'SUBMITTED',
    attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) MarkNotificationSubmitted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationSubmitted, id)
	return err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :one
INSERT INTO user_notification_settings (user_id, telegram_chat_id, enabled, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE
SET telegram_chat_id = EXCLUDED.telegram_chat_id,
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING user_id, telegram_chat_id, enabled, updated_at
`

type UpsertNotificationSettingsParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	TelegramChatID *string     `json:"telegram_chat_id"`
	Enabled        bool        `json:"enabled"`
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) (UserNotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertNotificationSettings, arg.UserID, arg.TelegramChatID, arg.Enabled)
	var i UserNotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.TelegramChatID,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}
