// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phase_a.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserTasks = `-- name: CountUserTasks :one
SELECT count(*)::bigint AS count
FROM tasks
WHERE user_id = $1
  AND status IN ('PENDING', 'RUNNING', 'PAUSED')
`

func (q *Queries) CountUserTasks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProxy = `-- name: CreateProxy :one
INSERT INTO proxies (endpoint, status)
VALUES ($1, $2)
RETURNING id, endpoint, status, created_at
`

type CreateProxyParams struct {
	Endpoint string      `json:"endpoint"`
	Status   ProxyStatus `json:"status"`
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, createProxy, arg.Endpoint, arg.Status)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, plan_type, active)
VALUES ($1, $2, true)
RETURNING id, user_id, plan_type, active, created_at
`

type CreateSubscriptionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PlanType PlanType    `json:"plan_type"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.PlanType)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanType,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, query, status)
VALUES ($1, $2, 'PENDING')
RETURNING id, user_id, query, status, created_at
`

type CreateTaskParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Query  string      `json:"query"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.UserID, arg.Query)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email)
VALUES ($1)
RETURNING id, email, created_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getActiveSubscriptionByUser = `-- name: GetActiveSubscriptionByUser :one
SELECT id, user_id, plan_type, active, created_at
FROM subscriptions
WHERE user_id = $1 AND active = true
`

func (q *Queries) GetActiveSubscriptionByUser(ctx context.Context, userID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByUser, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanType,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getItemByAvitoID = `-- name: GetItemByAvitoID :one
SELECT id, avito_id, title, created_at
FROM items
WHERE avito_id = $1
`

func (q *Queries) GetItemByAvitoID(ctx context.Context, avitoID string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByAvitoID, avitoID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.AvitoID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanMaxTasks = `-- name: GetPlanMaxTasks :one
SELECT max_tasks
FROM plan_limits
WHERE plan_type = $1
`

func (q *Queries) GetPlanMaxTasks(ctx context.Context, planType PlanType) (int32, error) {
	row := q.db.QueryRow(ctx, getPlanMaxTasks, planType)
	var max_tasks int32
	err := row.Scan(&max_tasks)
	return max_tasks, err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO items (avito_id, title)
VALUES ($1, $2)
RETURNING id, avito_id, title, created_at
`

type InsertItemParams struct {
	AvitoID string `json:"avito_id"`
	Title   string `json:"title"`
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem, arg.AvitoID, arg.Title)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.AvitoID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveProxies = `-- name: ListActiveProxies :many
SELECT id, endpoint, status, created_at
FROM proxies
WHERE status = 'ACTIVE'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveProxies(ctx context.Context) ([]Proxy, error) {
	rows, err := q.db.Query(ctx, listActiveProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
