// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeMagicLinkChallenge = `-- name: ConsumeMagicLinkChallenge :one
UPDATE magic_link_challenges
SET consumed_at = now()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, email, token_hash, role_hint, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeMagicLinkChallenge(ctx context.Context, tokenHash string) (MagicLinkChallenge, error) {
	row := q.db.QueryRow(ctx, consumeMagicLinkChallenge, tokenHash)
	var i MagicLinkChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.RoleHint,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countAvitoAccounts = `-- name: CountAvitoAccounts :one
SELECT count(*)::bigint AS count
FROM avito_accounts
`

func (q *Queries) CountAvitoAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAvitoAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAvitoAccount = `-- name: CreateAvitoAccount :one
INSERT INTO avito_accounts (label, status, external_ref)
VALUES ($1, $2, $3)
RETURNING id, label, status, external_ref, created_at, updated_at
`

type CreateAvitoAccountParams struct {
	Label       string             `json:"label"`
	Status      AvitoAccountStatus `json:"status"`
	ExternalRef string             `json:"external_ref"`
}

func (q *Queries) CreateAvitoAccount(ctx context.Context, arg CreateAvitoAccountParams) (AvitoAccount, error) {
	row := q.db.QueryRow(ctx, createAvitoAccount, arg.Label, arg.Status, arg.ExternalRef)
	var i AvitoAccount
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMagicLinkChallenge = `-- name: CreateMagicLinkChallenge :one
INSERT INTO magic_link_challenges (email, token_hash, role_hint, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, token_hash, role_hint, expires_at, consumed_at, created_at
`

type CreateMagicLinkChallengeParams struct {
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	RoleHint  UserRole           `json:"role_hint"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMagicLinkChallenge(ctx context.Context, arg CreateMagicLinkChallengeParams) (MagicLinkChallenge, error) {
	row := q.db.QueryRow(ctx, createMagicLinkChallenge,
		arg.Email,
		arg.TokenHash,
		arg.RoleHint,
		arg.ExpiresAt,
	)
	var i MagicLinkChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.RoleHint,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserWithRole = `-- name: CreateUserWithRole :one
INSERT INTO users (email, role)
VALUES ($1, $2)
RETURNING id, email, created_at, role
`

type CreateUserWithRoleParams struct {
	Email string   `json:"email"`
	Role  UserRole `json:"role"`
}

func (q *Queries) CreateUserWithRole(ctx context.Context, arg CreateUserWithRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithRole, arg.Email, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const grantUserService = `-- name: GrantUserService :one
INSERT INTO user_service_entitlements (user_id, service_code)
VALUES ($1, $2)
RETURNING user_id, service_code, created_at
`

type GrantUserServiceParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServiceCode string      `json:"service_code"`
}

func (q *Queries) GrantUserService(ctx context.Context, arg GrantUserServiceParams) (UserServiceEntitlement, error) {
	row := q.db.QueryRow(ctx, grantUserService, arg.UserID, arg.ServiceCode)
	var i UserServiceEntitlement
	err := row.Scan(&i.UserID, &i.ServiceCode, &i.CreatedAt)
	return i, err
}

const hasUserService = `-- name: HasUserService :one
SELECT EXISTS (
    SELECT 1
    FROM user_service_entitlements
    WHERE user_id = $1 AND service_code = $2
)
`

type HasUserServiceParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServiceCode string      `json:"service_code"`
}

func (q *Queries) HasUserService(ctx context.Context, arg HasUserServiceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserService, arg.UserID, arg.ServiceCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPlanLimits = `-- name: ListPlanLimits :many
SELECT plan_type, max_tasks, max_watches
FROM plan_limits
ORDER BY plan_type ASC
`

func (q *Queries) ListPlanLimits(ctx context.Context) ([]PlanLimit, error) {
	rows, err := q.db.Query(ctx, listPlanLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanLimit{}
	for rows.Next() {
		var i PlanLimit
		if err := rows.Scan(&i.PlanType, &i.MaxTasks, &i.MaxWatches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductServices = `-- name: ListProductServices :many
SELECT code, title, shipped, created_at
FROM product_services
ORDER BY code ASC
`

func (q *Queries) ListProductServices(ctx context.Context) ([]ProductService, error) {
	rows, err := q.db.Query(ctx, listProductServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductService{}
	for rows.Next() {
		var i ProductService
		if err := rows.Scan(
			&i.Code,
			&i.Title,
			&i.Shipped,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserServices = `-- name: ListUserServices :many
SELECT e.user_id, e.service_code, e.created_at
FROM user_service_entitlements e
WHERE e.user_id = $1
ORDER BY e.service_code ASC
`

func (q *Queries) ListUserServices(ctx context.Context, userID pgtype.UUID) ([]UserServiceEntitlement, error) {
	rows, err := q.db.Query(ctx, listUserServices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserServiceEntitlement{}
	for rows.Next() {
		var i UserServiceEntitlement
		if err := rows.Scan(&i.UserID, &i.ServiceCode, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
