package tokens

import "strings"

// RenderLRTRule returns the always-applied Cursor LRT core rule body.
func RenderLRTRule() string {
	genList := strings.Join([]string{
		PathEnvExample,
		PathDesignCSS,
		PathCompose,
		PathSQLC,
		PathDockerfile,
		PathAppFace,
		PathLRTRule,
		PathVitekPolicyRule,
	}, "`, `")

	return `---
description: Live Runtime Truth (LRT) Core Rules for Go Engine
globs: **/*
alwaysApply: true
---
# LRT Engineering Rules for AI & Developers

1. NEVER create or ask for text documentation files (e.g., ARCHITECTURE.md, TZ.md, DESIGN.md, ADR-*.md).
2. The Single Source of Truth (SoT) for business invariants is ` + "`tests/contracts/*_test.go`" + `. Always run ` + "`task test:contracts`" + ` to verify domain logic.
3. The SoT for domain states, enums, and models is the PostgreSQL schema (` + "`db/migrations`" + `) and types generated by ` + "`sqlc`" + `. Never use raw string literals for states in Go code.
4. Only ` + PathREADME + ` (local setup) and ` + PathDEPLOY + ` (CI/CD) are permitted as prose documentation on disk.
5. Every refactoring or feature MUST start with an updated contract in ` + "`tests/contracts/`" + ` that fails (RED) before implementation (GREEN).
6. Product identity and all env/design/infra/tooling/HTTP/app-face/landing literals live in ` + "`internal/tokens`" + `. Regenerate derived files with ` + "`task tokens:gen`" + ` (` + "`" + genList + "`" + `). Never edit those by hand.
7. Multi-tenant Avito SaaS platform (multiple product services). First shipped service = ` + ServiceCodeListingSearch + `; other services (e.g. listing warmup) are reserved, not built yet. Domains: landing ` + ProductDomainLanding + ` (magic link only), platform ` + ProductDomainApp + ` (USER + ADMIN shell). HTTP surface = ` + "`tokens.HTTP*Routes`" + ` policy only; anything else → 404. Auth = Magic Link (HTTP request/consume/logout + sessions). Avito accounts + proxies CRUD via admin HTTP; live lists UI later when contracted. listing_search processors: stub | avito (HTTP JSON) | rod (Chrome SERP, filter URLs only; ` + EnvRodUserDataDir + `). Chrome-in-worker image — later when contracted. Telegram / Redis / feed matcher — later only when contracted. Do not add packages or deps ahead of contracts.
8. Commit messages that change invariants MUST include an ` + "`LRT-VERIFY:`" + ` block naming the contract file and GREEN status.
9. Keep Day-0 surface minimal: no empty packages, no docs that describe missing artifacts, no unused infra (compose/env/deps) without a consumer + contract.
10. Transport (` + PathTransport + `) must NOT import ` + PathRepository + ` directly — use ` + PathService + ` (CONTRACT-ARCH-001).
`
}

// RenderVitekPolicyMDC returns the architecture anti-drift rule (complements RenderLRTRule).
func RenderVitekPolicyMDC() string {
	return `---
description: Vitek Architecture & Anti-Drift Policy
globs: **/*
---
# Vitek Layer Architecture

1. Transport (` + PathTransport + `) → service only; never ` + PathRepository + `.
2. Domain (` + PathDomain + `) → tokens only; never transport, repository, or service.
3. Fitness function: ` + "`tests/contracts/architecture_fitness_test.go`" + ` (CONTRACT-ARCH-001).
`
}
